version: '3.9'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes: 
      - ./db:/var/lib/postgresql/data
      # - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  api:
    build: ./api/
    image: api-service
    ports: 
      - "5000:5000"
    command: flask run --host 0.0.0.0
    volumes: 
      - ./api/:/app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    # links:
    #   - db
    # depends_on:
    #   - db

volumes:
  db:
    driver: local